### ISSUE TITLE
Feature Request: Add images

### ISSUE THREAD

**Issue by arayray** [rkusa/dcs-scratchpad#11]
Similar to the functionality of the kneeboard, can the ability to add images be added? This would effectively replace the kneeboard totally.

**Comment by rkusa** [comment]
Interesting feature request. It would probably be really hard to get images to work inline of the editable text, but maybe adding image pages (pages that show an image an no editable text at all) could be a feasible feature. I personally don't see a huge benefit compared to adding the images to the integrated Kneeboard, since the Kneeboard has better support for custom key-/buttonbindings.  I'll still keep it in mind though 👍

**Comment by rkusa** [comment]
I'll close this for now as not planned. I might reconsider it in the future, but for now I don't see it worth the effort to compete with the existing kneeboard for images. Thanks for the suggestion anyway!
