### ISSUE TITLE
Feature request: Add In-Game Button to Clear the Current Scratch Pad...

### ISSUE THREAD

**Issue by gkleinfe** [rkusa/dcs-scratchpad#32]
Playing in VR, I sometimes need to clear the scratchpad.  I find myself blindly searching around my keyboard for the del key.  Possibly add a button that will clear the current scratchpad or currently selected text.

**Comment by rkusa** [comment]
Thank you for the suggestion! I can totally see that this would be useful for you (and others, as it was requested before). Though, I personally prefer to have fewer buttons and instead use my keyboard blindly. So I am afraid that I am not going to add a button like this. However, due to other feature requests, I am going to start looking into ways to allow others to extend the Scratchpad via plugins. So there could be a plugin for such a button in the feature.
