### ISSUE TITLE
No +L/L shows up in F10 map where it did before 

### ISSUE THREAD

**Issue by speed-of-heat** [rkusa/dcs-scratchpad#34]
I don't seem to be able to get the +L/L to show there is no check box in F10 Map mode.

I was using this successfully in the same map in the previous release...  this is single player

**Comment by speed-of-heat** [comment]
seems now to work after pressing cycling through a couple of times ... ?

**Comment by rkusa** [comment]
Thanks for the report! I am afraid that I cannot reproduce the issue. For me it works the same as before both in SP and MP, i.e., checkbox is always visible, and checking it always brings up the +L/L button. I'll keep an eye on it thought.

**Comment by speed-of-heat** [comment]
it's very strange, it wont show up in Mission planner, it will show up in F10 map once the mission has started, it wont show up in the main menu (no utility for it there i know)

**Comment by speed-of-heat** [comment]
![Screen_220905_153542](https://user-images.githubusercontent.com/64099136/188473493-8140632f-1d83-4591-9800-307df8d01226.png)
main menu = no box

![Screen_220905_153635](https://user-images.githubusercontent.com/64099136/188473543-d7bc4683-7749-4cb6-abb6-a6ed8ff4c207.png)
Mission Planning = No box

![Screen_220905_153751](https://user-images.githubusercontent.com/64099136/188473601-d54bbacf-4183-48db-ae43-d037bfff5a1a.png)
In Mission = Box

![Screen_220905_153810](https://user-images.githubusercontent.com/64099136/188473638-2b4f7b69-13fe-407b-8cc2-5a2cade49527.png)
F10 in Mission = Box

**Comment by rkusa** [comment]
@speed-of-heat thanks for the additional details! The only difference between my and your setup I can spot is that I use multiple pages - so I also have the prev and next buttons. I'll test again without them - maybe it only happens if they are not shown.

**Comment by rkusa** [comment]
> it wont show up in Mission planner, it will show up in F10 map once the mission has started, it wont show up in the main menu (no utility for it there i know)

I just properly re-read your last messages, and what you are describing is the intended behaviour. It was the same behaviour for the previous version, too.

The checkbox and +L/L are not shown in the menu and mission editor, because the APIs to make them work don't work there. The APIs only work when you are in an actual mission.
I am not sure about the mission planner. I've never used it before. How do you open it? But I suspect it is the basically the same as the mission editor, so the APIs will not work.

The only actual bug I can see on your screenshot is that the position of the checkbox is off, if you don't have the prev/next buttons (which is the case if you have only one single page).
