### ISSUE TITLE
f14 rio

### ISSUE THREAD

**Issue by Thesantjo** [rkusa/dcs-scratchpad#48]
idk if this is only an issue from the rio seat or from pilot seat aswell but scratchpad gives wrong format in f14 rio seat atleast

**Comment by rkusa** [comment]
@Zrad522 As I don't fly the F14, and since the F14 setting was contributed from someone else, I only quickly checked a youtube video about the F14, and there the entry was in DMS and not DDM. Is this different between pilot and rio?

Regarding MGRS: the way they are returned from DCS, there is unfortunately no easily way to round/truncate them (possible but a lot of effort).

**Comment by rkusa** [comment]
As a matter of fact, the youtube video might have done it wrong. I've talked to a squadron member of mine and he confirmed that `{DDM = {precision = 1}}` is correct. I'll update it when I find the time

**Comment by rkusa** [comment]
Updated. Thanks again for bringing this up 👍
